server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # безопасные заголовки
  add_header X-Content-Type-Options "nosniff" always;

  # кеш статики
  location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|webp|ico|woff2?)$ {
    expires 30d;
    access_log off;
    add_header Cache-Control "public";
  }

  location / {
    try_files $uri $uri/ $uri/index.html =404;
  }
}
